version: "3.7"

services:
  pg_master:
    image: bitc0d/pg-master
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbtest
      - PG_REP_USER=user_rep
      - PG_REP_PASSWORD=password_rep
    networks:
      - pg-net

  pg_slave:
    image: bitc0d/pg-slave
    volumes:
      - pg_slave:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbtest
      - PG_REP_USER=user_rep
      - PG_REP_PASSWORD=password_rep
    networks:
      - pg-net

networks:
  pg-net:
    name: pg-net

volumes:
  pg_data:
    name: pg_data
    driver: local
  pg_slave:
    name: pg_slave1
    driver: local
